server:
  servlet:
    context-path: /procrear
  port: 8086

app:
  service-inventory:
    subject-service: http://localhost:8081/procrear/subject
    student-service: http://localhost:8082/procrear/student
    course-service: http://localhost:8083/procrear/course
