server:
  servlet:
    context-path: /procrear
  port: 8086

app:
  service-inventory:
    subject-service: http://localhost:8081/procrear
    student-service: http://localhost:8082/procrear
    course-service: http://localhost:8083/procrear
