spring:
  datasource:
    url: jdbc:h2:mem:student-service
    driver-class-name: org.h2.Driver
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /procrear
  port: 8082
