spring:
  datasource:
    url: jdbc:h2:mem:subject-service
    driver-class-name: org.h2.Driver
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /procrear
  port: 8081
